In [11]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option("display.max_columns", None)

# Better looking plots
plt.style.use("ggplot")

# Display plots inside the notebook
%matplotlib inline

In [13]:
df = pd.read_csv("../dataset/used_cars_data.csv")

In [14]:
df.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [15]:
df.shape

(7253, 14)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   str
 2   Location           7253 non-null   str
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   str
 6   Transmission       7253 non-null   str
 7   Owner_Type         7253 non-null   str
 8   Mileage            7251 non-null   str
 9   Engine             7207 non-null   str
 10  Power              7207 non-null   str
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   str
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), str(9)
memory usage: 793.4 KB

In [17]:
df.columns.tolist()

['S.No.',
 'Name',
 'Location',
 'Year',
 'Kilometers_Driven',
 'Fuel_Type',
 'Transmission',
 'Owner_Type',
 'Mileage',
 'Engine',
 'Power',
 'Seats',
 'New_Price',
 'Price']

In [19]:
df.tail

<bound method NDFrame.tail of       S.No.                                               Name    Location  \
0         0                             Maruti Wagon R LXI CNG      Mumbai
1         1                   Hyundai Creta 1.6 CRDi SX Option        Pune
2         2                                       Honda Jazz V     Chennai
3         3                                  Maruti Ertiga VDI     Chennai
4         4                    Audi A4 New 2.0 TDI Multitronic  Coimbatore
...     ...                                                ...         ...
7248   7248                  Volkswagen Vento Diesel Trendline   Hyderabad
7249   7249                             Volkswagen Polo GT TSI      Mumbai
7250   7250                             Nissan Micra Diesel XV     Kolkata
7251   7251                             Volkswagen Polo GT TSI        Pune
7252   7252  Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...       Kochi

      Year  Kilometers_Driven Fuel_Type Transmission Owner_Type     Mileage  \
0     2010              72000       CNG       Manual      First  26.6 km/kg
1     2015              41000    Diesel       Manual      First  19.67 kmpl
2     2011              46000    Petrol       Manual      First   18.2 kmpl
3     2012              87000    Diesel       Manual      First  20.77 kmpl
4     2013              40670    Diesel    Automatic     Second   15.2 kmpl
...    ...                ...       ...          ...        ...         ...
7248  2011              89411    Diesel       Manual      First  20.54 kmpl
7249  2015              59000    Petrol    Automatic      First  17.21 kmpl
7250  2012              28000    Diesel       Manual      First  23.08 kmpl
7251  2013              52262    Petrol    Automatic      Third   17.2 kmpl
7252  2014              72443    Diesel    Automatic      First   10.0 kmpl

       Engine      Power  Seats  New_Price  Price
0      998 CC  58.16 bhp    5.0        NaN   1.75
1     1582 CC  126.2 bhp    5.0        NaN  12.50
2     1199 CC   88.7 bhp    5.0  8.61 Lakh   4.50
3     1248 CC  88.76 bhp    7.0        NaN   6.00
4     1968 CC  140.8 bhp    5.0        NaN  17.74
...       ...        ...    ...        ...    ...
7248  1598 CC  103.6 bhp    5.0        NaN    NaN
7249  1197 CC  103.6 bhp    5.0        NaN    NaN
7250  1461 CC   63.1 bhp    5.0        NaN    NaN
7251  1197 CC  103.6 bhp    5.0        NaN    NaN
7252  2148 CC    170 bhp    5.0        NaN    NaN

[7253 rows x 14 columns]>

In [20]:
df.describe()

             S.No.         Year  Kilometers_Driven        Seats        Price
count  7253.000000  7253.000000       7.253000e+03  7200.000000  6019.000000
mean   3626.000000  2013.365366       5.869906e+04     5.279722     9.479468
std    2093.905084     3.254421       8.442772e+04     0.811660    11.187917
min       0.000000  1996.000000       1.710000e+02     0.000000     0.440000
25%    1813.000000  2011.000000       3.400000e+04     5.000000     3.500000
50%    3626.000000  2014.000000       5.341600e+04     5.000000     5.640000
75%    5439.000000  2016.000000       7.300000e+04     5.000000     9.950000
max    7252.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [22]:
df.describe(include="object")

/tmp/ipykernel_49086/702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Name,Location,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,New_Price
count,7253,7253,7253,7253,7253,7251,7207,7207,1006
unique,2041,11,5,2,4,450,150,386,625
top,Mahindra XUV500 W8 2WD,Mumbai,Diesel,Manual,First,17.0 kmpl,1197 CC,74 bhp,95.13 Lakh
freq,55,949,3852,5204,5952,207,732,280,6

In [23]:
df.isnull().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [24]:
df.isnull().sum().sort_values(ascending=False)

New_Price            6247
Price                1234
Seats                  53
Engine                 46
Power                  46
Mileage                 2
Fuel_Type               0
Kilometers_Driven       0
Year                    0
Location                0
Name                    0
S.No.                   0
Transmission            0
Owner_Type              0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.dtypes

S.No.                  int64
Name                     str
Location                 str
Year                   int64
Kilometers_Driven      int64
Fuel_Type                str
Transmission             str
Owner_Type               str
Mileage                  str
Engine                   str
Power                    str
Seats                float64
New_Price                str
Price                float64
dtype: object